/* -*- c++ -*- */
/* 
 * Copyright 2017 <+YOU OR YOUR COMPANY+>.
 * 
 * This is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 * 
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this software; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */


#ifndef INCLUDED_PACKETIZER_PACKET_ENCODER_H
#define INCLUDED_PACKETIZER_PACKET_ENCODER_H

#include <packetizer/api.h>
#include <gnuradio/digital/api.h>
#include <gnuradio/tagged_stream_block.h>
#include <gnuradio/digital/constellation.h>
#include <gnuradio/digital/packet_header_default.h>
#include <gnuradio/block.h>

namespace gr {
  namespace packetizer {

    /*!
     * \brief Packet Encoder
     * \ingroup packetizer
     *
     * \details
     * This block creates packets from an incoming data stream. The incoming stream should be an
     * unpacked byte stream with 1 bit/byte, and tags should indicate the packet start and payload length.
     * The packets have the following format: preamble, header, payload. 
     * The preamble is given as a modulated sequence (for example, -1 and 1 for BPSK). 
     * The Pulse shape vector block can be used to modulate the preamble.
     * The data of the header is generated by the header formatter. 
     * The header will be mapped to symbols using the given header constellations. (differentially encoded if \param diff_header is set)
     * The data will be mapped to symbols using the given payload constellations.
     * Between the different packets, there will be zero_padding number of zero samples..
     * In case Whiten is set to true, the binary data will be whitened by XORing with a precomputed sequence.
     */
    class PACKETIZER_API packet_encoder : virtual public gr::tagged_stream_block
    {
     public:
      typedef boost::shared_ptr<packet_encoder> sptr;

      /*!
       * \param preamble Sequence of modulated preamble symbols (BPSK: -1 and 1)
       * \param constel_header Constellation object for header
       * \param constel_payload Constellation object for payload
       * \param header_formatter Header formatter object
       * \param diff_header Boolean indicating to use differential encoding for header
       * \param diff_payload Boolean indicating to use differential encoding for payload
       * \param lengthtagname Name of tag that indicates the start of the payload data and the length of it.
       * \param zero_padding Amount of zero samples between two packets. 0 to disable. 
       * \param whiten Indicate whether to whiten packet data
       * \param itemsize No effect yet. Input is always unpacked bytes (1bit/symbol), output is always complex symbols.
       */
      static sptr make(
        const std::vector<int> preamble, 
        const gr::digital::constellation_sptr constel_header, 
        const gr::digital::constellation_sptr constel_payload, 
        const gr::digital::packet_header_default::sptr &header_formatter, 
        const bool diff_header = 0,
        const bool diff_payload = 0,
        const std::string &lengthtagname = "packet_len", 
        const int zero_padding = 0,
        const bool whiten = 0,
        const size_t itemsize = 1
        );


    };

  } // namespace packetizer
} // namespace gr

#endif /* INCLUDED_packetizer_PACKET_ENCODER_H */

